import abjad
import evans

articulation_handler_one = evans.ArticulationHandler(
    articulation_list=[
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tenuto",
        "default",
        "default",
        "default",
        "accent",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tenuto",
        "accent",
        "default",
        "tenuto",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tremolo",
        "tremolo",
        "tremolo",
        "tremolo",
    ],
    continuous=True,
    name="articulation_handler_one",
)

test_fingering = abjad.WoodwindFingering(
    name="flute",
    center_column=("one", "two", "three", "four", "five", "six"),
    left_hand=("bes", "b", "gis"),
    right_hand=("bes", "d", "dis", "ees", "cis", "c", "gz"),
)
mark = abjad.Markup(contents=test_fingering(), direction=abjad.Down)
