import abjad
import evans

articulation_handler_one = evans.ArticulationHandler(
    articulation_list=[
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tenuto",
        "default",
        "default",
        "default",
        "accent",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tenuto",
        "accent",
        "default",
        "tenuto",
        "default",
        "default",
        "default",
        "default",
        "default",
        "default",
        "tremolo",
        "tremolo",
        "tremolo",
        "tremolo",
    ],
    continuous=True,
    name="articulation_handler_one",
)
