import pathlib

import abjad
import baca
import evans
from chalk_line.materials.pitch.segment_03.clef_handlers import clef_handlers
from chalk_line.materials.score_structure.instruments import instruments as insts
from chalk_line.materials.score_structure.score_structure import score
from chalk_line.materials.score_structure.segment_03.time_signatures import (
    time_signatures,
)
from chalk_line.materials.timespans.segment_03.convert_timespans import (
    segment_03_rhythm_timespans,
    segment_03_timespans,
)

c = abjad.LilyPondLiteral(
    r"""
        _ \markup {
            \override #'(font-name . "STIXGeneral")
            \with-color #white
            \right-column {
                \line { "\hspace #0.75 .........................." }
                \with-color #black
                \line { \hspace #0.75 Spring Valley, Oh. }
                \with-color #black
                \line { \hspace #0.75 April 2020 }
            }
        }
    """,
    format_slot="absolute_after",
)

charts = [
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four five six)) (lh . (b)) (rh . (cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four five six)) (lh . (b)) (rh . ()))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7.5",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four fiveR six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three fourR five six)) (lh . (b)) (rh . (d)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (three four five six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (twoR three four five six)) (lh . ()) (rh . (cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one three four five six)) (lh . (b)) (rh . (cis c gz)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two threeR four five six)) (lh . (b)) (rh . (d)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three five six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one twoR three four five six)) (lh . (b)) (rh . (c gz)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two threeR fourR six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one twoR three four fiveR six)) (lh . (b)) (rh . (cis c gz)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #10",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one twoR three four fiveR six)) (lh . (b)) (rh . (dis c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four)) (lh . (b)) (rh . (ees dis d)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three five)) (lh . (b)) (rh . (dis c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
]

maker = evans.SegmentMaker(
    instruments=insts,
    names=["Flute"],
    rhythm_timespans=segment_03_rhythm_timespans,
    handler_timespans=segment_03_timespans,
    score_template=score,
    time_signatures=time_signatures,
    clef_handlers=clef_handlers,
    voicewise_direct_attachments=[
        [
            (
                baca.select().leaves(pitched=True).get([1]),
                abjad.ColorFingering(3),
            ),
            (
                baca.select().leaves(pitched=True).get([2]),
                abjad.ColorFingering(1),
            ),
            (
                baca.select().leaves(pitched=True).get([3]),
                abjad.ColorFingering(2),
            ),
            (
                baca.select().leaves(pitched=True).get([17]),
                abjad.ColorFingering(2),
            ),
            (
                baca.select().leaves(pitched=True).get([18]),
                abjad.ColorFingering(1),
            ),
            (
                baca.select().leaves(pitched=True).get([21]),
                abjad.ColorFingering(3),
            ),
            (
                baca.select().leaves(pitched=True).get([22]),
                abjad.ColorFingering(1),
            ),
            (
                baca.select().leaves(pitched=True).get([23]),
                abjad.ColorFingering(2),
            ),
            (
                baca.select().leaves(pitched=True).get([38]),
                abjad.ColorFingering(2),
            ),
            (
                baca.select().leaves(pitched=True).get([39]),
                abjad.ColorFingering(1),
            ),
            (
                baca.select().leaves(pitched=True).get([58]),
                abjad.ColorFingering(3),
            ),
            (
                baca.select().leaves(pitched=True).get([59]),
                abjad.ColorFingering(1),
            ),
            (
                baca.select().leaves(pitched=True).get([60]),
                abjad.ColorFingering(2),
            ),
            (baca.select().leaves(pitched=True).get([4]), charts[0]),
            (baca.select().leaves(pitched=True).get([12]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([12]), charts[1]),
            (baca.select().leaves(pitched=True).get([16]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([19]), charts[2]),
            (baca.select().leaves(pitched=True).get([20]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([24]), charts[0]),
            (baca.select().leaves(pitched=True).get([33]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([33]), charts[1]),
            (baca.select().leaves(pitched=True).get([37]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([40]), charts[2]),
            (baca.select().leaves(pitched=True).get([41]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([41]), charts[3]),
            (baca.select().leaves(pitched=True).get([42]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([42]), charts[4]),
            (baca.select().leaves(pitched=True).get([44]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([44]), charts[5]),
            (baca.select().leaves(pitched=True).get([46]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([46]), charts[6]),
            (baca.select().leaves(pitched=True).get([50]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([50]), charts[7]),
            (baca.select().leaves(pitched=True).get([57]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([61]), charts[8]),
            (baca.select().leaves(pitched=True).get([65]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([65]), charts[9]),
            (baca.select().leaves(pitched=True).get([67]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([67]), charts[10]),
            (baca.select().leaves(pitched=True).get([70]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([70]), charts[11]),
            (baca.select().leaves(pitched=True).get([72]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([72]), charts[12]),
            (baca.select().leaves(pitched=True).get([74]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([74]), charts[13]),
            (baca.select().leaves(pitched=True).get([77]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([78]), charts[14]),
            (baca.select().leaves(pitched=True).get([80]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([80]), charts[15]),
            (baca.select().leaves(pitched=True).get([83]), abjad.StopTextSpan()),
            (baca.select().leaves(pitched=True).get([83]), charts[6]),
            (baca.select().leaves().get([-1]), abjad.StopTextSpan()),
        ]
    ],
    tuplet_bracket_noteheads=True,
    add_final_grand_pause=True,
    score_includes=[
        "/Users/evansdsg2/abjad/docs/source/_stylesheets/abjad.ily",
        "/Users/evansdsg2/Scores/chalk_line/chalk_line/build/first_stylesheet.ily",
    ],
    parts_includes=[
        "/Users/evansdsg2/abjad/docs/source/_stylesheets/abjad.ily",
        "/Users/evansdsg2/Scores/chalk_line/chalk_line/build/parts_stylesheet.ily",
    ],
    segment_name="segment_03",
    current_directory=pathlib.Path(__file__).parent,
    build_path=pathlib.Path(__file__).resolve().parent.parent.parent / "build",
    cutaway=False,
    beam_pattern="meter",
    beam_rests=False,
    barline="|.",
    tempo=((1, 4), 59),
    rehearsal_mark="Afterimage",
    page_break_counts=[90],
    midi=False,
    colophon=c,
)

maker.build_segment()
