import pathlib

import abjad
import baca
import evans
from chalk_line.materials.pitch.segment_03.clef_handlers import clef_handlers
from chalk_line.materials.score_structure.instruments import instruments as insts
from chalk_line.materials.score_structure.score_structure import score
from chalk_line.materials.score_structure.segment_03.time_signatures import (
    time_signatures,
)
from chalk_line.materials.timespans.segment_03.convert_timespans import (
    segment_03_rhythm_timespans,
    segment_03_timespans,
)

c = abjad.LilyPondLiteral(
    r"""
        _ \markup {
            \override #'(font-name . "STIXGeneral")
            \with-color #white
            \right-column {
                \line { "\hspace #0.75 .........................." }
                \with-color #black
                \line { \hspace #0.75 Spring Valley, Oh. }
                \with-color #black
                \line { \hspace #0.75 April 2020 }
            }
        }
    """,
    format_slot="absolute_after",
)

charts = [
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four five six)) (lh . (b)) (rh . (cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four five six)) (lh . (b)) (rh . ()))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7.5",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four fiveR six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three fourR five six)) (lh . (b)) (rh . (d)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (three four five six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (twoR three four five six)) (lh . ()) (rh . (cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one three four five six)) (lh . (b)) (rh . (cis c gz)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two threeR four five six)) (lh . (b)) (rh . (d)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three five six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one twoR three four five six)) (lh . (b)) (rh . (c gz)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two threeR fourR six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one twoR three four fiveR six)) (lh . (b)) (rh . (cis c gz)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four six)) (lh . (b)) (rh . (c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #10",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one twoR three four fiveR six)) (lh . (b)) (rh . (dis c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three four)) (lh . (b)) (rh . (ees dis d)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
    abjad.LilyPondLiteral(
        [
            r"- \abjad-solid-line-with-hook",
            r"- \tweak bound-details.left.text \markup {",
            r"    \hspace #2",
            r"    \override #'(graphical . #t)",
            r"    \override #'(size . 0.6)",
            r"    \override #'(thickness . 0.125)",
            r"    \woodwind-diagram",
            r"    #'flute",
            r"    #'((cc . (one two three five)) (lh . (b)) (rh . (dis c cis)))",
            r"}",
            r"- \tweak padding #5",
            r"- \tweak staff-padding #7",
            r"- \tweak bound-details.right.padding #2",
            r"\startTextSpan",
        ],
        format_slot="after",
    ),
]

maker = evans.SegmentMaker(
    instruments=insts,
    names=["Flute"],
    rhythm_timespans=segment_03_rhythm_timespans,
    handler_timespans=segment_03_timespans,
    score_template=score,
    time_signatures=time_signatures,
    clef_handlers=clef_handlers,
    commands=[
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(3),
            selector=baca.pleaf(1),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(1),
            selector=baca.pleaf(2),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(2),
            selector=baca.pleaf(3),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(2),
            selector=baca.pleaf(17),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(1),
            selector=baca.pleaf(18),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(3),
            selector=baca.pleaf(21),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(1),
            selector=baca.pleaf(22),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(2),
            selector=baca.pleaf(23),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(2),
            selector=baca.pleaf(38),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(1),
            selector=baca.pleaf(39),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(3),
            selector=baca.pleaf(58),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(1),
            selector=baca.pleaf(59),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.ColorFingering(2),
            selector=baca.pleaf(60),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[0],
            selector=baca.pleaf(4),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(12),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[1],
            selector=baca.pleaf(12),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(16),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[2],
            selector=baca.pleaf(19),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(20),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[0],
            selector=baca.pleaf(24),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(33),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[1],
            selector=baca.pleaf(33),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(37),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[2],
            selector=baca.pleaf(40),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(41),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[3],
            selector=baca.pleaf(41),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(42),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[4],
            selector=baca.pleaf(42),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(44),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[5],
            selector=baca.pleaf(44),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(46),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[6],
            selector=baca.pleaf(46),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(50),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[7],
            selector=baca.pleaf(50),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(57),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[8],
            selector=baca.pleaf(61),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(65),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[9],
            selector=baca.pleaf(65),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(67),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[10],
            selector=baca.pleaf(67),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(70),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[11],
            selector=baca.pleaf(70),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(72),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[12],
            selector=baca.pleaf(72),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(74),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[13],
            selector=baca.pleaf(74),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(77),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[14],
            selector=baca.pleaf(78),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(80),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[15],
            selector=baca.pleaf(80),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.pleaf(83),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=charts[6],
            selector=baca.pleaf(83),
            voice="Voice 1",
        ),
        evans.Command(
            command="attach",
            indicator=abjad.StopTextSpan(),
            selector=baca.select().leaf(-1),
            voice="Voice 1",
        ),
    ],
    tuplet_bracket_noteheads=True,
    add_final_grand_pause=True,
    score_includes=[
        "/Users/evansdsg2/abjad/docs/source/_stylesheets/abjad.ily",
        "/Users/evansdsg2/Scores/chalk_line/chalk_line/build/first_stylesheet.ily",
    ],
    parts_includes=[
        "/Users/evansdsg2/abjad/docs/source/_stylesheets/abjad.ily",
        "/Users/evansdsg2/Scores/chalk_line/chalk_line/build/parts_stylesheet.ily",
    ],
    segment_name="segment_03",
    current_directory=pathlib.Path(__file__).parent,
    build_path=pathlib.Path(__file__).resolve().parent.parent.parent / "build",
    cutaway=False,
    beam_pattern="meter",
    beam_rests=False,
    barline="|.",
    tempo=((1, 4), 59),
    rehearsal_mark="Afterimage",
    page_break_counts=[90],
    midi=False,
    colophon=c,
)

maker.build_segment()
